import { Scrip } from '../../common/types';
import Parser from './Parser';

const DATA_HEADER = '/* SCRIPTCADDY DATA (AUTOGENERATED)';
const DATA_FOOTER = '*/';

export default class JavascriptParser extends Parser {
  parse(fileContents: string): Scrip {
    const [scriptBody, configBody = ''] = fileContents.split(`\n${DATA_HEADER}\n`);
    return {
      scriptBody,
      scriptConfigBody: configBody.split(`\n${DATA_FOOTER}`)[0],
    };
  }

  compose(scrip: Scrip): string {
    return [
      scrip.scriptBody,
      DATA_HEADER,
      scrip.scriptConfigBody,
      DATA_FOOTER,
    ].join('\n');
  }
}
